"""THE RULE CATALOGUE - every rule in the system, declared here and nowhere else.

One file to read and one file to edit. Each entry says what the rule is called,
what passing looks like, how severe a failure is, and which facts it may read;
the function that decides it lives in the module named on the line, grouped by
BRD section - so the catalogue also tells you where to go.

Section headings and print order are NOT here: they live in
src/templates/post-check-template.md, which declares with its
`<!-- rules: ... -->` markers which criteria print under which section, and
verify_template asserts every rule below appears there exactly once.

The import-time check at the bottom is why a mistyped fact path cannot become a
silent unchecked row: it raises when this module is first imported, which happens
before any run.
"""

from src.rules import criteria, dossier, ews, fraud, identity, operation
from src.rules.engine import Rule, validate_needs


RULES: tuple[Rule, ...] = (
    # --- BRD 2.1 - Verify the customer information ---------------------------------
    # Answers BRD row 13 (section 2.1) - one row, seven identity fields;
    # V08 and V09 compare the RM's own entries on LOS against the same documents.
    Rule(id="V01",
         title="Tên khách hàng khớp giữa LOS và chứng từ",
         expected="Tên KH trên mọi chứng từ trùng với tên trên LOS",
         severity="high",
         needs=("los.customer_name", "doc.customer_name_values"),
         check=identity.check_customer_name),
    Rule(id="V02",
         title="Mã số thuế khớp giữa LOS và chứng từ",
         expected="MST trên mọi chứng từ trùng với MST trên LOS",
         severity="high",
         needs=("los.tax_code", "doc.tax_code_values"),
         check=identity.check_tax_code),
    Rule(id="V03",
         title="Địa chỉ khớp giữa LOS và chứng từ",
         expected="Địa chỉ trên mọi chứng từ trùng với địa chỉ trên LOS",
         severity="medium",
         needs=("los.address", "doc.address_values"),
         check=identity.check_address),
    Rule(id="V04",
         title="Tên chủ doanh nghiệp khớp giữa LOS và chứng từ",
         expected="Tên CDN trên mọi chứng từ trùng với tên trên LOS",
         severity="high",
         needs=("los.owner_name", "doc.owner_name_values"),
         check=identity.check_owner_name),
    Rule(id="V05",
         title="Số CCCD chủ doanh nghiệp khớp giữa LOS và chứng từ",
         expected="CCCD trên mọi chứng từ trùng với CCCD trên LOS",
         severity="high",
         needs=("los.owner_id_number", "doc.owner_id_number_values"),
         check=identity.check_owner_id_number),
    Rule(id="V06",
         title="Năm sinh chủ doanh nghiệp khớp giữa LOS và chứng từ",
         expected="Năm sinh CDN trên mọi chứng từ trùng với năm sinh trên LOS",
         severity="medium",
         needs=("los.owner_birth_year", "doc.owner_birth_year_values"),
         check=identity.check_owner_birth_year),
    Rule(id="V07",
         title="Ngành nghề khớp giữa LOS, ĐKKD và khảo sát thực địa",
         expected="Ngành nghề trên ba nguồn cùng mô tả một hoạt động",
         severity="medium",
         needs=("los.industry", "los.gso_code", "doc.industry_on_registration",
               "doc.industry_on_sitevisit"),
         check=identity.check_industry),
    Rule(id="V08",
         title="Khảo sát thực địa RM nhập trên LOS khớp với báo cáo nộp kèm",
         expected="Ngành nghề RM nhập trùng với hồ sơ LOS và báo cáo khảo sát",
         severity="medium",
         needs=("los.sitevisit_online.industry", "los.industry",
               "doc.industry_on_sitevisit"),
         check=identity.check_sitevisit_online),
    Rule(id="V09",
         title="BCTC RM nhập trên LOS khớp với BCTC nộp kèm",
         expected="Cùng kỳ báo cáo và cùng loại báo cáo",
         severity="medium",
         needs=("los.financials_online.report_year", "los.financials_online.report_type",
               "doc.financials.report_year", "doc.financials.report_type"),
         check=identity.check_financials_online),
    Rule(id="V10",
         title="Ảnh khảo sát thực địa phù hợp với chân dung khách hàng",
         expected="Bộ ảnh cho thấy đủ số dấu hiệu kỳ vọng của chân dung trên LOS",
         severity="medium",
         needs=("los.persona", "los.is_site_visit", "doc.sitevisit_photo_evidence"),
         check=identity.check_persona_photos),

    # --- BRD 2.2 - Signs of suspected fraud ----------------------------------------
    # Answers BRD row 19 (section 2.2). Row 20 is out of scope - see the module docstring.
    Rule(id="F01",
         title="Thông tin khách hàng nhất quán xuyên suốt các chứng từ",
         expected="MST, tên KH, địa chỉ và tên CDN chỉ có một giá trị trên toàn hồ sơ",
         severity="high",
         needs=("doc.tax_code_values", "doc.customer_name_values"),
         check=fraud.check_internal_consistency),

    # --- BRD 2.3.a - Document checklist per program --------------------------------
    # Answers BRD rows 22, 24, 25, 26, 27 (section 2.3, document checklist group).
    Rule(id="P01",
         title="Xác định được chương trình cấp tín dụng của khách hàng",
         expected="Chương trình LOS trả ra nằm trong danh mục đã khai (B1CP/MISA/PL++)",
         severity="high",
         needs=("los.program", "los.tax_code"),
         check=dossier.check_program),
    Rule(id="P02",
         title="Đủ hồ sơ theo checklist của chương trình",
         expected="Mọi đầu mục bắt buộc của chương trình đều có mặt trong hồ sơ",
         severity="high",
         needs=("los.program", "los.is_site_visit", "doc.types_present"),
         check=dossier.check_checklist),
    Rule(id="P03",
         title="Định dạng file phù hợp theo quy định",
         expected="Mọi file thuộc định dạng Word/Excel/PDF/XML",
         severity="low",
         needs=("doc.extensions",),
         check=dossier.check_file_formats),
    Rule(id="P04",
         title="Chứng từ khách hàng cung cấp đủ chữ ký và con dấu",
         expected="Mọi chứng từ thuộc nhóm bắt buộc đều có cả chữ ký và con dấu",
         severity="high",
         needs=("los.program", "doc.signature_and_seal"),
         check=dossier.check_signature_and_seal),
    Rule(id="P05",
         title="BCTC có chữ ký điện tử",
         expected="BCTC khách hàng cung cấp mang chữ ký điện tử",
         severity="medium",
         needs=("doc.financials.has_digital_signature",),
         check=dossier.check_digital_signature),
    Rule(id="P06",
         title="BCTC cân đối: tổng tài sản bằng tổng nguồn vốn",
         expected="Tổng tài sản = tổng nguồn vốn",
         severity="high",
         needs=("doc.financials.total_assets", "doc.financials.total_capital"),
         check=dossier.check_balance),
    Rule(id="P07",
         title="Kỳ BCTC phù hợp theo quy định",
         expected="Active trước 30/4 dùng BCTC N-2; từ 30/4 dùng BCTC N-1",
         severity="medium",
         needs=("doc.financials.report_year", "t24.booking_date"),
         check=dossier.check_report_period),

    # --- BRD 2.3.b - Credit criteria the unit assessed -----------------------------
    Rule(id="C01",
         title="Ngành nghề không trọng tâm thì CCR bằng 100%",
         expected="Ngành nghề không trọng tâm buộc CCR = 100%",
         severity="high",
         needs=("los.gso_code", "t24.ccr"),
         check=criteria.check_industry_ccr),
    Rule(id="C02",
         title="Ngành nghề không thuộc danh mục hạn chế cấp tín dụng",
         expected="Mã GSO không nằm trong danh mục ngành nghề hạn chế",
         severity="high",
         needs=("los.gso_code",),
         check=criteria.check_restricted_industry),
    Rule(id="C03",
         title="Nợ xấu, nợ cần chú ý của KH/CDN so với tiêu chí chương trình",
         expected="Nhóm nợ của KH và CDN không vượt ngưỡng của chương trình",
         severity="high",
         needs=("los.program", "cic.customer_debt_group_at_approval",
               "cic.owner_debt_group_at_approval"),
         check=criteria.check_debt_group),
    Rule(id="C04",
         title="KH/CDN nằm trong BL/WL so với tiêu chí chương trình",
         expected="KH và CDN không có tên trong BL/WL tại thời điểm phê duyệt",
         severity="high",
         needs=("blwl.customer_at_approval", "blwl.owner_at_approval"),
         check=criteria.check_blwl),
    Rule(id="C05",
         title="KH/CDN ở luồng thu hồi nợ AMC so với tiêu chí chương trình",
         expected="KH và CDN không ở luồng thu hồi nợ tại thời điểm phê duyệt",
         severity="high",
         needs=("amc.customer_at_approval", "amc.owner_at_approval"),
         check=criteria.check_amc),
    Rule(id="C06",
         title="Cổ đông góp vốn: nhóm nợ, BL/WL và luồng thu hồi nợ",
         expected="Không cổ đông nào có nợ cần chú ý, nằm trong BL/WL hay ở luồng thu hồi nợ",
         severity="medium",
         needs=("los.shareholders", "cic.shareholder_debt_groups_at_approval",
               "blwl.shareholders_at_approval", "amc.shareholders_at_approval"),
         check=criteria.check_shareholders),

    # --- BRD 2.3.c - The unit's operations -----------------------------------------
    # Answers BRD rows 34, 35, 36, 37 (section 2.3, operations group);
    # O05-O08 answer no BRD row.
    Rule(id="O01",
         title="HMTD được hạch toán khi phê duyệt còn hiệu lực",
         expected="Ngày hạch toán trên T24 nằm trong thời gian hiệu lực của lô phê duyệt",
         severity="high",
         needs=("t24.booking_date", "los.batch_valid_from", "los.batch_valid_to"),
         check=operation.check_within_validity),
    Rule(id="O02",
         title="Tổng giá trị HMTD không vượt quá giá trị hội sở trả ra",
         expected="HMTD active trên T24, tổng và từng sản phẩm, không vượt HMTD phê duyệt trên LOS",
         severity="high",
         needs=("t24.active_limit", "t24.active_limit_by_product",
               "los.approved_limit", "los.approved_limit_by_product"),
         check=operation.check_limit_not_exceeded),
    Rule(id="O03",
         title="BBC hạch toán đúng CCR",
         expected="KH không đáp ứng tiêu chí tín chấp thì CCR = 100%",
         severity="high",
         needs=("t24.ccr", "los.program", "los.gso_code",
               "cic.customer_debt_group_at_approval", "cic.owner_debt_group_at_approval",
               "blwl.customer_at_approval", "blwl.owner_at_approval"),
         check=operation.check_ccr_booking),
    Rule(id="O04",
         title="Cấu trúc TSBĐ phù hợp theo quy định",
         expected="CCR dưới 100% thì mọi TSBĐ phải là PTVT hoặc BĐS",
         severity="high",
         needs=("t24.ccr", "collateral.items"),
         check=operation.check_collateral_structure),
    Rule(id="O05",
         title="HMTD phê duyệt không vượt mức khách hàng đề nghị (*)",
         expected="HMTD trên LOS không lớn hơn HMTD khách hàng đề nghị trong hồ sơ",
         severity="medium",
         needs=("doc.proposal.requested_limit", "los.approved_limit"),
         check=operation.check_requested_vs_approved),
    Rule(id="O06",
         title="TSBĐ kê trong hồ sơ khớp với TSBĐ trên hệ thống (*)",
         expected="Cùng loại tài sản, và tổng giá trị chênh không quá 40%",
         severity="medium",
         needs=("doc.proposal.collateral_items", "collateral.items"),
         check=operation.check_collateral_matches_dossier),
    Rule(id="O07",
         title="TSBĐ đăng ký tại CIC còn hiệu lực khi CCR dưới 100% (*)",
         expected="CCR dưới 100% thì trên CIC phải còn ít nhất một tài sản đang thế chấp",
         severity="high",
         needs=("t24.ccr", "cic.collateral_items"),
         check=operation.check_cic_security_live),
    Rule(id="O08",
         title="Giá trị TSBĐ trên hệ thống khớp với đăng ký tại CIC (*)",
         expected="Tổng giá trị TSBĐ trên hệ thống chênh không quá 40% so với CIC",
         severity="medium",
         needs=("collateral.items", "cic.collateral_items"),
         check=operation.check_cic_collateral_value),

    # --- BRD 2.4 - Early credit-risk signals ---------------------------------------
    # Answers BRD rows 39, 40, 41, 43, 44, 45 (section 2.4).
    Rule(id="E01",
         title="KH và CDN có nợ xấu, nợ có vấn đề tại thời điểm post-check",
         expected="Nhóm nợ CIC của KH và CDN dưới ngưỡng cảnh báo",
         severity="high",
         needs=("cic.customer_debt_group_at_postcheck", "cic.owner_debt_group_at_postcheck",
               "case.postcheck_date"),
         check=ews.check_debt_group_now),
    Rule(id="E02",
         title="KH và CDN nằm trong BL/WL tại thời điểm post-check",
         expected="KH và CDN không có tên trong BL/WL",
         severity="high",
         needs=("blwl.customer_at_postcheck", "blwl.owner_at_postcheck",
               "case.postcheck_date"),
         check=ews.check_blwl_now),
    Rule(id="E03",
         title="KH và CDN ở luồng thu hồi nợ AMC tại thời điểm post-check",
         expected="KH và CDN không ở luồng thu hồi nợ",
         severity="high",
         needs=("amc.customer_at_postcheck", "amc.owner_at_postcheck",
               "case.postcheck_date"),
         check=ews.check_amc_now),
    Rule(id="E04",
         title="Cổ đông góp vốn tại thời điểm post-check",
         expected="Không cổ đông nào có nợ cần chú ý, nằm trong BL/WL hay ở luồng thu hồi nợ",
         severity="medium",
         needs=("cic.shareholder_debt_groups_at_postcheck", "blwl.shareholders_at_postcheck",
               "amc.shareholders_at_postcheck", "case.postcheck_date"),
         check=ews.check_shareholders_now),
    Rule(id="E05",
         title="DT STO trên LOS so với DT trên BCTC năm gần nhất",
         expected="Chênh lệch không quá 40%",
         severity="medium",
         needs=("los.sto_revenue", "los.financials_online.revenue",
               "los.financials_online.report_year"),
         check=ews.check_sto_vs_application),
    Rule(id="E06",
         title="DT và LNST trên BCTC so với Virac",
         expected="Cùng kỳ báo cáo, bằng nhau",
         severity="medium",
         needs=("doc.financials.report_year", "doc.financials.revenue_current_year",
               "doc.financials.net_profit_current_year", "virac.revenue_by_year",
               "virac.net_profit_by_year"),
         check=ews.check_financials_vs_virac),
    Rule(id="E07",
         title="DT trên BCTC biến động giữa kỳ trước và kỳ báo cáo",
         expected="Biến động không quá 40%",
         severity="medium",
         needs=("doc.financials.revenue_prior_year", "doc.financials.revenue_current_year"),
         check=ews.check_revenue_swing),
    Rule(id="E08",
         title="Giao dịch dòng tiền: số lần phát sinh PDLD",
         expected="Số LD quá hạn (PDLD) không vượt mức cho phép",
         severity="medium",
         needs=("cashflow.pdld_count",),
         check=ews.check_cashflow),
)


validate_needs(RULES)
